/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.inventory;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class InventoryManagerApp {
    @Test void appHasAGreeting() {
        InventoryManager classUnderTest = new InventoryManager();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
